name: DQuiz_Console
description: A quiz taking console application for CS 5381
# version: 1.0.0
# homepage: https://www.github.com/DeveloperJose

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
